#------------------------
#GitHub Action Linter
#Sosnin Valentin  2024.
#------------------------

name: lint

on:
  push

jobs:
  linting:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        with:
          python-version: '3.x'
        uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          pip install poetry flake8 pyyaml
          make install
      - name: Lint with flake8
        run: |
          make lint